- name: Create admin user
  ansible.builtin.user:
    name: "{{ admin_user }}"
    groups: "{{ admin_groups }}"
    append: true
    shell: /bin/bash
    create_home: true

- name: Create SSH directory
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/.ssh"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0700'
  when: admin_ssh_key | length > 0

- name: Install admin SSH key
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_ssh_key }}"
    state: present
  when: admin_ssh_key | length > 0

- name: Set user shell
  ansible.builtin.user:
    name: "{{ admin_user }}"
    shell: "{{ admin_shell }}"

- name: Remove old user
  ansible.builtin.user:
    name: "{{ remove_user }}"
    state: absent
    remove: true
  when: remove_user | length > 0
