- name: Create systemd service
  ansible.builtin.template:
    src: simple-app.service.j2
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    mode: '0644'
  notify: Reload systemd

- name: Enable service
  ansible.builtin.systemd:
    name: "{{ systemd_service_name }}"
    enabled: true
    state: started
    daemon_reload: true

- name: Restart service on demand
  ansible.builtin.systemd:
    name: "{{ systemd_service_name }}"
    state: restarted
  when: restart_service | bool
